# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token e3bec6579546fa9eb1ef269b0d68dd8c3acee965

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token e3bec6579546fa9eb1ef269b0d68dd8c3acee965

{
  "status": "DRAFT"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

### 
POST http://127.0.0.1:8000/api/advertisements/4/favorite/
Authorization: Token e3bec6579546fa9eb1ef269b0d68dd8c3acee965

### 
GET http://127.0.0.1:8000/api/advertisements/favorites/
Authorization: Token 5268cb1ef23d8cc5d29492c2edbc9e144a337648